"""V1.0 character budgets and conservative task heuristics; not empirically validated."""
FEEDBACK_CONTEXT_MAX_CHARS = 800
MEMORY_SUMMARY_MAX_CHARS = 1200
HISTORY_ITEM_MAX_CHARS = 600
RELEVANT_HISTORY_LIMIT = 5
PLANNER_CONTEXT_MAX_CHARS = 12000
MEMORY_SUMMARY_EVENT_THRESHOLD = 10
MEMORY_SUMMARY_BATCH_LIMIT = 20
SUMMARY_CONTEXT_MAX_CHARS = 16000
DEFAULT_TASK_MINUTES = 60
MAX_TASK_MINUTES = 240
MIN_TASK_MINUTES = 5

KNOWLEDGE_PROMOTION_COMPLETIONS = 2
PRACTICE_PROMOTION_COMPLETIONS = 2
